version: '3'
services:
  builder:
    image: audithsoftworks/uniform
    volumes:
    - .:/home/audith
    working_dir: /home/audith
    stdin_open: true
    ports:
    - 3000:3000
    - 3001:3001
    - 8080:8080
    networks:
      static-network:
        ipv4_address: 172.71.0.2
networks:
  static-network:
    ipam:
      config:
      - subnet: 172.71.0.0/16
