#!/bin/bash

echo "Sending JS to appspot.com"
curl \
	-s \
	--data-urlencode js_code@jquery.uniform.js \
	--data output_info=compiled_code \
	--data output_format=text \
	--data compilation_level=SIMPLE_OPTIMIZATIONS \
	http://closure-compiler.appspot.com/compile > jquery.uniform.min.js
